import { assembleBrandBrain } from "./brain";
import { makeJob } from "./jobs";
import { dailyBriefFromReading, interpret, weeklyFromItems } from "./engine";
import { signalFingerprint } from "./signals";
import type { BriefProject, ProjectIntelligence } from "../../types/project";
import type {
  BrainRevision,
  IntelligenceItem,
  MonitoredCompetitor,
  Signal,
  WatchState,
} from "../../types/intelligence";

export type DemoKind = "north" | "late" | "field" | "kiln";

function daysAgo(now: string, days: number): string {
  const date = new Date(now);
  date.setUTCDate(date.getUTCDate() - days);
  return date.toISOString();
}

function signal(input: Omit<Signal, "fingerprint" | "confidence" | "status" | "evidence" | "metadata"> & {
  fingerprint?: string;
  confidence?: Signal["confidence"];
  status?: Signal["status"];
  evidence?: string[];
  metadata?: Record<string, string>;
}): Signal {
  const next: Signal = {
    confidence: "moderate",
    status: "new",
    evidence: [],
    metadata: {},
    fingerprint: "",
    ...input,
  };
  next.fingerprint = signalFingerprint(next);
  return next;
}

function competitor(input: MonitoredCompetitor): MonitoredCompetitor {
  return input;
}

function item(input: IntelligenceItem): IntelligenceItem {
  return input;
}

export function attachDemoWatch(
  kind: DemoKind,
  project: BriefProject,
  intelligence: ProjectIntelligence,
  now: string,
): BriefProject {
  const brain = assembleBrandBrain(project, intelligence);
  const built = kind === "north"
    ? north(project.id, now)
    : kind === "late"
      ? late(project.id, now)
      : kind === "field"
        ? field(project.id, now)
        : kiln(project.id, now);
  const { reading, memory } = interpret({
    brain,
    signals: built.signals,
    reactions: [],
    memory: [],
    catalogue: built.catalogue,
    now,
    source: "demo",
    period: "Last 90 days · demo sample",
  });
  const watch: WatchState = {
    signals: built.signals,
    readings: [reading],
    reactions: [],
    jobs: built.jobs,
    revisions: built.revisions,
    memory,
    competitors: built.competitors,
    dailyBriefs: [dailyBriefFromReading(reading, project.businessName || "this client", now)],
    weeklyReads: [weeklyFromItems(reading, now, built.weekly)],
    updatedAt: now,
  };
  return { ...project, watch };
}

function jobsFor(brandId: string, now: string) {
  return [
    makeJob(brandId, "demo-social", "competitor_social", "daily", now, true),
    makeJob(brandId, "demo-search", "search_themes", "daily", now, true),
    makeJob(brandId, "demo-news", "category_news", "hourly", now, true),
    makeJob(brandId, "demo-market", "prices", "weekly", now, true),
    makeJob(brandId, "website-html", "website", "manual", now, false),
  ];
}

function north(brandId: string, now: string) {
  const signals: Signal[] = [
    signal({
      id: "north-repair",
      brandId,
      type: "competitor_content_theme_rising",
      sourceType: "social",
      sourceProvider: "demo-social",
      title: "Repair and restoration showed up in three workshops",
      description: "Three of the five workshops in the demo sample published repair or restoration content in the last 18 days. None used that theme in the previous 90-day sample.",
      observedAt: daysAgo(now, 1),
      periodStart: daysAgo(now, 18),
      periodEnd: daysAgo(now, 1),
      entity: "Monitored workshops",
      entityId: "north-workshops",
      metric: "repair_posts",
      previousValue: "0",
      currentValue: "3 workshops",
      change: "New theme",
      origin: "demo",
      firstObservedAt: daysAgo(now, 18),
      lastObservedAt: daysAgo(now, 1),
      metadata: { temporal: "convergence", themes: "repair, restoration, longevity", material: "no" },
    }),
    signal({
      id: "north-search",
      brandId,
      type: "search_interest_change",
      sourceType: "search",
      sourceProvider: "demo-search",
      title: "Built-in dining bench searches rose",
      description: "In the demo search sample, interest in built-in dining benches rose over six weeks. Dining table, as a broad term, did not.",
      observedAt: daysAgo(now, 2),
      periodStart: daysAgo(now, 45),
      periodEnd: daysAgo(now, 2),
      entity: "Built-in dining bench",
      entityId: "query-dining-bench",
      metric: "search_interest",
      previousValue: "Quiet",
      currentValue: "Rising",
      change: "Rising",
      origin: "demo",
      firstObservedAt: daysAgo(now, 45),
      lastObservedAt: daysAgo(now, 2),
      metadata: { temporal: "acceleration", themes: "architectural joinery, dining, built-in" },
    }),
    signal({
      id: "north-process",
      brandId,
      type: "competitor_post_frequency_change",
      sourceType: "social",
      sourceProvider: "demo-social",
      title: "Process explainers have persisted for six weeks",
      description: "Late Timber's demo history shows a weekly material explainer. Posting around process has held for six weeks, and two other workshops have since tried similar posts.",
      observedAt: daysAgo(now, 4),
      periodStart: daysAgo(now, 42),
      periodEnd: daysAgo(now, 4),
      entity: "Late Timber",
      entityId: "c-late",
      metric: "process_posts",
      previousValue: "Occasional",
      currentValue: "Weekly",
      change: "Held",
      origin: "demo",
      firstObservedAt: daysAgo(now, 42),
      lastObservedAt: daysAgo(now, 4),
      metadata: { temporal: "persistence", themes: "process, material" },
    }),
    signal({
      id: "north-followers",
      brandId,
      type: "competitor_follower_change",
      sourceType: "social",
      sourceProvider: "demo-social",
      title: "Late Timber's follower count moved in the demo sample",
      description: "Demo figures only: 12,200 followers 90 days ago, 18,400 in the latest sample. The fixture ties the acceleration to the material series. This is not a live count.",
      observedAt: daysAgo(now, 1),
      periodStart: daysAgo(now, 90),
      periodEnd: daysAgo(now, 1),
      entity: "Late Timber",
      entityId: "c-late",
      metric: "followers",
      previousValue: "12200 demo",
      currentValue: "18400 demo",
      change: "Demo movement",
      origin: "demo",
      firstObservedAt: daysAgo(now, 90),
      lastObservedAt: daysAgo(now, 1),
      metadata: { temporal: "acceleration", once: "yes", themes: "followers" },
    }),
    signal({
      id: "north-timber",
      brandId,
      type: "material_price_change",
      sourceType: "market",
      sourceProvider: "demo-market",
      title: "Timber prices ticked up in the demo sample",
      description: "The demo price series shows a modest timber move over the quarter. No live commodity feed is connected.",
      observedAt: daysAgo(now, 6),
      periodStart: daysAgo(now, 90),
      periodEnd: daysAgo(now, 6),
      entity: "Timber",
      entityId: "timber",
      metric: "price",
      previousValue: "Demo baseline",
      currentValue: "Slightly higher",
      change: "Small",
      origin: "demo",
      firstObservedAt: daysAgo(now, 90),
      lastObservedAt: daysAgo(now, 6),
      metadata: { temporal: "persistence", themes: "timber, material" },
    }),
    signal({
      id: "north-headline",
      brandId,
      type: "competitor_website_change",
      sourceType: "website",
      sourceProvider: "demo-social",
      title: "Oak Room changed a homepage line",
      description: "In the demo sample, one homepage headline changed. The offer underneath did not.",
      observedAt: daysAgo(now, 1),
      periodStart: daysAgo(now, 7),
      periodEnd: daysAgo(now, 1),
      entity: "Oak Room",
      entityId: "c-oak",
      metric: "headline",
      previousValue: "Previous line",
      currentValue: "New line",
      change: "Wording",
      origin: "demo",
      firstObservedAt: daysAgo(now, 1),
      lastObservedAt: daysAgo(now, 1),
      metadata: { temporal: "once", themes: "headline" },
    }),
    signal({
      id: "north-news",
      brandId,
      type: "category_news",
      sourceType: "news",
      sourceProvider: "demo-news",
      title: "A trade piece about kitchen trends",
      description: "Demo news item. It mentions kitchens in general and never the kind of joinery this workshop wants.",
      observedAt: daysAgo(now, 3),
      periodStart: daysAgo(now, 3),
      periodEnd: daysAgo(now, 3),
      entity: "Trade press",
      entityId: "news-kitchens",
      metric: "mention",
      previousValue: "",
      currentValue: "Published",
      change: "New",
      origin: "demo",
      firstObservedAt: daysAgo(now, 3),
      lastObservedAt: daysAgo(now, 3),
      metadata: { temporal: "once", themes: "kitchens", clientLink: "no" },
    }),
  ];

  const catalogue: IntelligenceItem[] = [
    item({
      id: "north-change-repair",
      kind: "change",
      eyebrow: "Competitors",
      headline: "Three competitors are suddenly talking about repair.",
      evidence: "Three of the five workshops being monitored published repair or restoration content during the last 18 days. None used that theme in the previous 90-day sample.",
      whyItMatters: "North Workshop treats longevity as part of the work, and currently has very little proof of what happens to a piece after it leaves the bench.",
      briefRead: "Do not copy a repair position yet. The more ownable move is to show pieces that have already lived in people's homes.",
      possibleMove: "Find three pieces made more than five years ago and document how they have aged.",
      signalIds: ["north-repair", "north-process"],
      evidenceIds: [],
      temporal: "convergence",
      strategyRelation: "support",
      hypothesisId: "longevity",
      epistemicStatus: "hypothesis",
      origin: "demo",
      rank: 1,
      bucket: "today",
    }),
    item({
      id: "north-opp-bench",
      kind: "opportunity",
      eyebrow: "Search and the brief",
      headline: "A built-in dining case study would meet a search the workshop actually wants.",
      evidence: "The client wants more architectural joinery. Demo search interest in built-in dining benches is rising. Few of the monitored workshops publish a detailed built-in case study. Process photography is already something this workshop can make.",
      whyItMatters: "The profitable offer and the language people are using are lining up, and the category is not showing the work in any depth.",
      briefRead: "This is not a reason to be louder. It is a reason to make one specific kind of work legible.",
      possibleMove: "Publish one built-in dining piece properly: the constraint, the joint, the room after a year.",
      signalIds: ["north-search", "north-repair"],
      evidenceIds: [],
      temporal: "acceleration",
      strategyRelation: "support",
      hypothesisId: "joinery-legibility",
      epistemicStatus: "hypothesis",
      origin: "demo",
      rank: 2,
      bucket: "week",
    }),
    item({
      id: "north-watch-timber",
      kind: "watch",
      eyebrow: "Materials",
      headline: "Timber moved a little. It does not change the month.",
      evidence: "The demo price series is slightly up over the quarter.",
      whyItMatters: "The workshop buys timber, so the number is allowed in the room. It is not a message.",
      briefRead: "Keep it on the bench. Do not turn a small commodity move into content.",
      possibleMove: "",
      signalIds: ["north-timber"],
      evidenceIds: [],
      temporal: "persistence",
      strategyRelation: "not_affect",
      hypothesisId: "",
      epistemicStatus: "observation",
      origin: "demo",
      rank: 4,
      bucket: "watching",
    }),
    item({
      id: "north-noise-followers",
      kind: "non_actionable",
      eyebrow: "Competitors",
      headline: "A follower count moved. That is not the story.",
      evidence: "Demo figures show Late Timber's audience count rising after a material series. The count itself is not verified.",
      whyItMatters: "It is easy to treat a bigger number as a brief. North Workshop's constraint is the right work, not a louder feed.",
      briefRead: "This probably doesn't matter. The useful question is what the series was about, and you already have that as a process pattern.",
      possibleMove: "",
      signalIds: ["north-followers"],
      evidenceIds: [],
      temporal: "once",
      strategyRelation: "not_affect",
      hypothesisId: "",
      epistemicStatus: "observation",
      origin: "demo",
      rank: 6,
      bucket: "watching",
    }),
    item({
      id: "north-noise-headline",
      kind: "non_actionable",
      eyebrow: "Websites",
      headline: "One homepage line changed.",
      evidence: "Oak Room's demo homepage wording moved. The offer did not.",
      whyItMatters: "Headline watching becomes a nervous habit.",
      briefRead: "This probably doesn't matter.",
      possibleMove: "",
      signalIds: ["north-headline"],
      evidenceIds: [],
      temporal: "once",
      strategyRelation: "not_affect",
      hypothesisId: "",
      epistemicStatus: "observation",
      origin: "demo",
      rank: 7,
      bucket: "watching",
    }),
    item({
      id: "north-hypothesis",
      kind: "hypothesis",
      eyebrow: "The current read",
      headline: "Making architectural joinery legible is getting stronger.",
      evidence: "Search language is moving toward built-in dining, and the repair conversation is really a longevity conversation.",
      whyItMatters: "It matches the work the workshop wants more of, and the proof it does not yet show.",
      briefRead: "This remains a hypothesis. Nothing here turns it into a fact.",
      possibleMove: "",
      signalIds: ["north-search", "north-repair"],
      evidenceIds: [],
      temporal: "persistence",
      strategyRelation: "support",
      hypothesisId: "joinery-legibility",
      epistemicStatus: "hypothesis",
      origin: "demo",
      rank: 3,
      bucket: "week",
    }),
    item({
      id: "north-challenge",
      kind: "challenge",
      eyebrow: "An earlier read",
      headline: "January treated process content as secondary. That may be worth another look.",
      evidence: "The March note in this history says process content started bringing qualified enquiries. The demo sample now shows competitors staying with process education.",
      whyItMatters: "An old assumption can sit quietly while the evidence moves.",
      briefRead: "We may need to revisit how secondary process really is. The manager decides. This is not a new channel plan.",
      possibleMove: "Look at which enquiries actually named the process, before changing the plan.",
      signalIds: ["north-process"],
      evidenceIds: [],
      temporal: "persistence",
      strategyRelation: "challenge",
      hypothesisId: "process-secondary",
      epistemicStatus: "hypothesis",
      origin: "demo",
      rank: 5,
      bucket: "week",
    }),
    item({
      id: "north-question",
      kind: "question",
      eyebrow: "Still unknown",
      headline: "Which pieces are old enough to show how the work ages?",
      evidence: "The library has a joint on the bench. It does not yet have a piece five years on.",
      whyItMatters: "The repair observation depends on proof the workshop may already have, off camera.",
      briefRead: "Ask before briefing anyone to manufacture a heritage story.",
      possibleMove: "",
      signalIds: ["north-repair"],
      evidenceIds: [],
      temporal: "",
      strategyRelation: "",
      hypothesisId: "",
      epistemicStatus: "observation",
      origin: "demo",
      rank: 8,
      bucket: "watching",
    }),
  ];

  const revisions: BrainRevision[] = [
    {
      version: 1,
      at: daysAgo(now, 80),
      summary: "January",
      previous: "",
      current: "Instagram looks secondary. The website has to make the work legible.",
      why: "Discovery and the first pass at channels.",
      evidenceIds: [],
      managerDecisionIds: [],
    },
    {
      version: 2,
      at: daysAgo(now, 40),
      summary: "March",
      previous: "Process content is a nice extra.",
      current: "Process content has started to bring qualified enquiries.",
      why: "Manager observation, stored so it is not overwritten later.",
      evidenceIds: [],
      managerDecisionIds: ["manager.march.process"],
    },
    {
      version: 3,
      at: daysAgo(now, 18),
      summary: "May",
      previous: "Process education looked particular to one workshop.",
      current: "Competitors are increasingly using process education.",
      why: "Demo social sample.",
      evidenceIds: [],
      managerDecisionIds: [],
    },
    {
      version: 4,
      at: daysAgo(now, 2),
      summary: "June",
      previous: "Architectural joinery was a private ambition.",
      current: "Search interest around architectural joinery, especially built-in dining, is up in the demo sample.",
      why: "Demo search sample, read against the brief.",
      evidenceIds: [],
      managerDecisionIds: [],
    },
  ];

  const competitors: MonitoredCompetitor[] = [
    competitor({
      id: "c-late",
      name: "Late Timber",
      website: "https://late.example",
      socialHandles: ["Instagram", "TikTok"],
      relationship: "direct",
      monitoredSources: ["demo-social", "website-html"],
      lastCheckedAt: daysAgo(now, 1),
      origin: "demo",
      snapshots: [
        { at: daysAgo(now, 90), origin: "demo", note: "Demo. 12,200 followers. Occasional finished-room posts.", metrics: { followers: "12200 demo" } },
        { at: daysAgo(now, 45), origin: "demo", note: "Demo. Weekly material explainer begins.", metrics: { followers: "15100 demo" } },
        { at: daysAgo(now, 1), origin: "demo", note: "Demo. 18,400 followers. Interaction in the fixture is higher. Not a live count.", metrics: { followers: "18400 demo" } },
      ],
    }),
    competitor({
      id: "c-oak",
      name: "Oak Room",
      website: "https://oak.example",
      socialHandles: ["Instagram", "TikTok"],
      relationship: "direct",
      monitoredSources: ["demo-social"],
      lastCheckedAt: daysAgo(now, 1),
      origin: "demo",
      snapshots: [
        { at: daysAgo(now, 90), origin: "demo", note: "No repair content in the sample.", metrics: {} },
        { at: daysAgo(now, 10), origin: "demo", note: "First restoration post in the sample.", metrics: {} },
      ],
    }),
    competitor({
      id: "c-field",
      name: "Field & Grain",
      website: "https://field.example",
      socialHandles: ["Instagram"],
      relationship: "direct",
      monitoredSources: ["demo-social"],
      lastCheckedAt: daysAgo(now, 2),
      origin: "demo",
      snapshots: [
        { at: daysAgo(now, 90), origin: "demo", note: "Craftsmanship language, finished interiors.", metrics: {} },
        { at: daysAgo(now, 12), origin: "demo", note: "Repair post appears.", metrics: {} },
      ],
    }),
  ];

  return {
    signals,
    catalogue,
    revisions,
    competitors,
    jobs: jobsFor(brandId, now),
    weekly: {
      persisted: ["Process explainers have held for six weeks in the demo sample."],
      disappeared: ["A one-day spike in a broad dining-table query. It did not hold."],
      convergence: ["Three workshops moved toward repair or restoration."],
      customerLanguage: ["Built-in dining bench, rather than dining table."],
      searchMovement: ["Built-in dining bench interest rose. The broad table term did not."],
      opportunities: ["A built-in dining case study, told through work that already exists."],
      hypothesesStrengthened: ["Architectural joinery should be made legible. Still a hypothesis."],
      hypothesesWeakened: ["Process content is merely secondary."],
      decisionsToReconsider: ["The January read that process can wait."],
    },
  };
}

function late(brandId: string, now: string) {
  const signals: Signal[] = [
    signal({
      id: "late-midweek",
      brandId,
      type: "search_interest_change",
      sourceType: "search",
      sourceProvider: "demo-search",
      title: "Midweek dining searches are ahead of last year's pattern",
      description: "Demo search sample. People are looking for weeknight tables earlier in the season than the same weeks last year.",
      observedAt: daysAgo(now, 1),
      periodStart: daysAgo(now, 21),
      periodEnd: daysAgo(now, 1),
      entity: "Midweek dining",
      entityId: "query-midweek",
      metric: "search_interest",
      previousValue: "Last year's pace",
      currentValue: "Ahead",
      change: "Ahead of season",
      origin: "demo",
      firstObservedAt: daysAgo(now, 21),
      lastObservedAt: daysAgo(now, 1),
      metadata: { temporal: "seasonality", themes: "midweek, dining, weeknight" },
    }),
    signal({
      id: "late-tuesday",
      brandId,
      type: "competitor_offer_change",
      sourceType: "social",
      sourceProvider: "demo-social",
      title: "Two nearby rooms pushed Tuesday offers",
      description: "Demo sample. Two competitors started naming Tuesday as a reason to book. Both framed it as a set menu, not a discount code.",
      observedAt: daysAgo(now, 2),
      periodStart: daysAgo(now, 14),
      periodEnd: daysAgo(now, 2),
      entity: "Nearby rooms",
      entityId: "late-competitors",
      metric: "tuesday_offers",
      previousValue: "0",
      currentValue: "2",
      change: "New",
      origin: "demo",
      firstObservedAt: daysAgo(now, 14),
      lastObservedAt: daysAgo(now, 2),
      metadata: { temporal: "novelty", themes: "tuesday, midweek, booking" },
    }),
    signal({
      id: "late-private",
      brandId,
      type: "emerging_search",
      sourceType: "search",
      sourceProvider: "demo-search",
      title: "Private dining is being asked for more often",
      description: "Demo search sample. Private dining queries rose, in the language of a weeknight room rather than a banquet.",
      observedAt: daysAgo(now, 3),
      periodStart: daysAgo(now, 30),
      periodEnd: daysAgo(now, 3),
      entity: "Private dining",
      entityId: "query-private",
      metric: "search_interest",
      previousValue: "Flat",
      currentValue: "Rising",
      change: "Rising",
      origin: "demo",
      firstObservedAt: daysAgo(now, 30),
      lastObservedAt: daysAgo(now, 3),
      metadata: { temporal: "acceleration", themes: "private dining, midweek" },
    }),
    signal({
      id: "late-reel",
      brandId,
      type: "competitor_engagement_change",
      sourceType: "social",
      sourceProvider: "demo-social",
      title: "One Reel travelled further than usual",
      description: "Demo sample. A single competitor Reel spiked for a day and then returned to the account's ordinary range.",
      observedAt: daysAgo(now, 1),
      periodStart: daysAgo(now, 1),
      periodEnd: daysAgo(now, 1),
      entity: "A nearby room",
      entityId: "late-reel",
      metric: "reel_reach",
      previousValue: "Ordinary",
      currentValue: "One spike",
      change: "One day",
      origin: "demo",
      firstObservedAt: daysAgo(now, 1),
      lastObservedAt: daysAgo(now, 1),
      metadata: { temporal: "once", once: "yes", themes: "reel" },
    }),
    signal({
      id: "late-event",
      brandId,
      type: "cultural_event",
      sourceType: "news",
      sourceProvider: "demo-news",
      title: "A neighbourhood festival weekend is on the calendar",
      description: "Demo local item. It sits two weeks out and will put more people on the street outside service.",
      observedAt: daysAgo(now, 2),
      periodStart: daysAgo(now, 2),
      periodEnd: daysAgo(now, 2),
      entity: "Neighbourhood",
      entityId: "late-festival",
      metric: "event",
      previousValue: "",
      currentValue: "Dated",
      change: "Upcoming",
      origin: "demo",
      firstObservedAt: daysAgo(now, 2),
      lastObservedAt: daysAgo(now, 2),
      metadata: { temporal: "seasonality", themes: "local, dining", clientLink: "yes", surface: "yes" },
    }),
  ];

  const catalogue: IntelligenceItem[] = [
    item({
      id: "late-change-midweek",
      kind: "change",
      eyebrow: "Search",
      headline: "Midweek demand is moving ahead of the usual seasonal pattern.",
      evidence: "Demo search has weeknight dining ahead of the same weeks last year. Two nearby rooms have started naming Tuesday as a reason to book.",
      whyItMatters: "Late Service wants fuller midweek seatings without discounting the room. The occasion is the constraint, not the feed.",
      briefRead: "The question is what makes a Tuesday feel worth leaving the house for. A louder Reel does not answer it.",
      possibleMove: "Look at the booking note people already use when they come back on a weeknight, and write to that.",
      signalIds: ["late-midweek", "late-tuesday"],
      evidenceIds: [],
      temporal: "seasonality",
      strategyRelation: "support",
      hypothesisId: "midweek-utilisation",
      epistemicStatus: "hypothesis",
      origin: "demo",
      rank: 1,
      bucket: "today",
    }),
    item({
      id: "late-opp-private",
      kind: "opportunity",
      eyebrow: "Demand",
      headline: "Private dining is being asked for in the language of a small room.",
      evidence: "Demo search for private dining is rising, and it clusters with midweek rather than with large parties.",
      whyItMatters: "A second seating story that still respects the room. It is not a banquet product.",
      briefRead: "If the room can take one extra table without breaking service, say so plainly. If it cannot, do not invent the offer.",
      possibleMove: "Confirm with the floor whether one midweek table can be held, then describe it as a weeknight, not an event.",
      signalIds: ["late-private", "late-midweek"],
      evidenceIds: [],
      temporal: "acceleration",
      strategyRelation: "support",
      hypothesisId: "midweek-utilisation",
      epistemicStatus: "hypothesis",
      origin: "demo",
      rank: 2,
      bucket: "week",
    }),
    item({
      id: "late-noise-reel",
      kind: "non_actionable",
      eyebrow: "Social",
      headline: "A Reel spiked for a day.",
      evidence: "One competitor post travelled, then stopped. Demo sample only.",
      whyItMatters: "It will show up in other tools as a format lesson.",
      briefRead: "This probably doesn't matter. One spike is not a change in how people decide to book.",
      possibleMove: "",
      signalIds: ["late-reel"],
      evidenceIds: [],
      temporal: "once",
      strategyRelation: "not_affect",
      hypothesisId: "",
      epistemicStatus: "observation",
      origin: "demo",
      rank: 5,
      bucket: "watching",
    }),
    item({
      id: "late-watch-event",
      kind: "watch",
      eyebrow: "The neighbourhood",
      headline: "A local weekend will put more people nearby.",
      evidence: "Demo calendar item, two weeks out.",
      whyItMatters: "It can fill a service that was already going to be full, and do nothing for Tuesday.",
      briefRead: "Useful as a staffing note. Weak as a brand idea.",
      possibleMove: "",
      signalIds: ["late-event"],
      evidenceIds: [],
      temporal: "seasonality",
      strategyRelation: "not_affect",
      hypothesisId: "",
      epistemicStatus: "observation",
      origin: "demo",
      rank: 4,
      bucket: "watching",
    }),
    item({
      id: "late-hypothesis",
      kind: "hypothesis",
      eyebrow: "The current read",
      headline: "The midweek occasion is the commercial problem. It is getting clearer, and it is still a hypothesis.",
      evidence: "Search, competitor offers, and the client's own aim point the same way.",
      whyItMatters: "Repeat behaviour and booking triggers matter more than a format trend.",
      briefRead: "Do not convert this into a content cadence. Ask whether Tuesday is actually emptier, and why people who come back decide to.",
      possibleMove: "",
      signalIds: ["late-midweek", "late-tuesday"],
      evidenceIds: [],
      temporal: "convergence",
      strategyRelation: "support",
      hypothesisId: "midweek-utilisation",
      epistemicStatus: "hypothesis",
      origin: "demo",
      rank: 3,
      bucket: "week",
    }),
  ];

  return {
    signals,
    catalogue,
    revisions: [
      {
        version: 1,
        at: daysAgo(now, 60),
        summary: "First read",
        previous: "",
        current: "The room is the product. Midweek is the gap.",
        why: "What the client said they wanted.",
        evidenceIds: [],
        managerDecisionIds: [],
      },
      {
        version: 2,
        at: daysAgo(now, 1),
        summary: "This week",
        previous: "Midweek follows the usual seasonal curve.",
        current: "Demo search is ahead of last year's curve, and neighbours are naming Tuesday.",
        why: "Demo sample, not a live index.",
        evidenceIds: [],
        managerDecisionIds: [],
      },
    ] satisfies BrainRevision[],
    competitors: [
      competitor({
        id: "late-room",
        name: "The other room",
        website: "",
        socialHandles: [],
        relationship: "direct",
        monitoredSources: ["demo-social", "demo-search"],
        lastCheckedAt: daysAgo(now, 1),
        origin: "demo",
        snapshots: [
          { at: daysAgo(now, 30), origin: "demo", note: "No Tuesday language.", metrics: {} },
          { at: daysAgo(now, 2), origin: "demo", note: "Tuesday set-menu language appears.", metrics: {} },
        ],
      }),
    ],
    jobs: jobsFor(brandId, now),
    weekly: {
      persisted: ["Midweek language has held for three weeks in the demo sample."],
      disappeared: ["A one-day Reel. It did not repeat."],
      convergence: ["Search and two competitors are both talking about weeknights."],
      customerLanguage: ["Weeknight table, private dining, not banquet."],
      searchMovement: ["Midweek dining is ahead of the seasonal pattern in the demo sample."],
      opportunities: ["Describe one midweek table if the floor can actually hold it."],
      hypothesesStrengthened: ["Utilisation, not awareness, is the commercial problem."],
      hypothesesWeakened: [],
      decisionsToReconsider: [],
    },
  };
}

function field(brandId: string, now: string) {
  const signals: Signal[] = [
    signal({
      id: "field-decisions",
      brandId,
      type: "competitor_content_theme",
      sourceType: "social",
      sourceProvider: "demo-social",
      title: "Two practices published the decision, not the building",
      description: "Demo sample. Two practices posted about a constraint they kept, before any finished photograph. Neither did this in the previous quarter.",
      observedAt: daysAgo(now, 1),
      periodStart: daysAgo(now, 20),
      periodEnd: daysAgo(now, 1),
      entity: "Peer practices",
      entityId: "field-peers",
      metric: "decision_posts",
      previousValue: "0",
      currentValue: "2",
      change: "New",
      origin: "demo",
      firstObservedAt: daysAgo(now, 20),
      lastObservedAt: daysAgo(now, 1),
      metadata: { temporal: "novelty", themes: "specifier, proof, decision" },
    }),
    signal({
      id: "field-tender",
      brandId,
      type: "category_news",
      sourceType: "news",
      sourceProvider: "demo-news",
      title: "A civic shortlist was announced",
      description: "Demo industry item. A shortlist named teams while the buildings are still unbuilt. Specifiers will see the names before any photograph exists.",
      observedAt: daysAgo(now, 2),
      periodStart: daysAgo(now, 2),
      periodEnd: daysAgo(now, 2),
      entity: "Civic shortlist",
      entityId: "field-shortlist",
      metric: "announcement",
      previousValue: "",
      currentValue: "Named",
      change: "Published",
      origin: "demo",
      firstObservedAt: daysAgo(now, 2),
      lastObservedAt: daysAgo(now, 2),
      metadata: { temporal: "once", themes: "tender, specifier, proof", clientLink: "yes", surface: "yes" },
    }),
    signal({
      id: "field-search",
      brandId,
      type: "related_query_change",
      sourceType: "search",
      sourceProvider: "demo-search",
      title: "Specifier language is showing up beside practice names",
      description: "Demo search sample. Queries pairing a building type with 'architect for' rose. Consumer 'dream home' language did not.",
      observedAt: daysAgo(now, 4),
      periodStart: daysAgo(now, 40),
      periodEnd: daysAgo(now, 4),
      entity: "Specifier queries",
      entityId: "query-specifier",
      metric: "related_queries",
      previousValue: "Flat",
      currentValue: "Rising",
      change: "Rising",
      origin: "demo",
      firstObservedAt: daysAgo(now, 40),
      lastObservedAt: daysAgo(now, 4),
      metadata: { temporal: "acceleration", themes: "specifier, architect" },
    }),
    signal({
      id: "field-linkedin",
      brandId,
      type: "competitor_engagement_change",
      sourceType: "social",
      sourceProvider: "demo-social",
      title: "One LinkedIn post outperformed that account once",
      description: "Demo sample. A single post travelled and was not followed by a second.",
      observedAt: daysAgo(now, 1),
      periodStart: daysAgo(now, 1),
      periodEnd: daysAgo(now, 1),
      entity: "A peer practice",
      entityId: "field-post",
      metric: "engagement",
      previousValue: "Ordinary",
      currentValue: "One spike",
      change: "Once",
      origin: "demo",
      firstObservedAt: daysAgo(now, 1),
      lastObservedAt: daysAgo(now, 1),
      metadata: { temporal: "once", once: "yes", themes: "linkedin" },
    }),
    signal({
      id: "field-rules",
      brandId,
      type: "regulatory_news",
      sourceType: "news",
      sourceProvider: "demo-news",
      title: "A consultation on documentation opened",
      description: "Demo regulatory note. It asks for clearer records of decisions on public work. It does not ban a style.",
      observedAt: daysAgo(now, 8),
      periodStart: daysAgo(now, 8),
      periodEnd: daysAgo(now, 8),
      entity: "Documentation consultation",
      entityId: "field-regs",
      metric: "consultation",
      previousValue: "",
      currentValue: "Open",
      change: "Opened",
      origin: "demo",
      firstObservedAt: daysAgo(now, 8),
      lastObservedAt: daysAgo(now, 8),
      metadata: { temporal: "novelty", themes: "proof, specifier", clientLink: "yes", surface: "yes" },
    }),
  ];

  const catalogue: IntelligenceItem[] = [
    item({
      id: "field-change",
      kind: "change",
      eyebrow: "The category",
      headline: "Peers are publishing the decision before the photograph.",
      evidence: "Two practices in the demo sample wrote about a constraint they kept. A civic shortlist named teams while the buildings are still unbuilt.",
      whyItMatters: "This practice is hired by people who decide early, on a long cycle. Proof of judgement travels further than a finished elevation, and it can exist sooner.",
      briefRead: "Authority here is the decision, explained. A project photograph is late evidence.",
      possibleMove: "Write one decision the principals would still defend, with the constraint named and the client identifiable only as far as they allow.",
      signalIds: ["field-decisions", "field-tender"],
      evidenceIds: [],
      temporal: "novelty",
      strategyRelation: "support",
      hypothesisId: "decision-proof",
      epistemicStatus: "hypothesis",
      origin: "demo",
      rank: 1,
      bucket: "today",
    }),
    item({
      id: "field-opp",
      kind: "opportunity",
      eyebrow: "Specifiers",
      headline: "The search language is the specifier's, not the househunter's.",
      evidence: "Demo queries pairing a building type with who the architect was are rising. Consumer dream-home language is not.",
      whyItMatters: "It agrees with a long buying cycle and with the people who meet the work before a client does.",
      briefRead: "Do not chase a broader audience. Make the existing expertise easier for a specifier to trust.",
      possibleMove: "One note a specifier could forward: the decision, the constraint, what was refused.",
      signalIds: ["field-search", "field-decisions"],
      evidenceIds: [],
      temporal: "acceleration",
      strategyRelation: "support",
      hypothesisId: "specifier-audience",
      epistemicStatus: "hypothesis",
      origin: "demo",
      rank: 2,
      bucket: "week",
    }),
    item({
      id: "field-challenge",
      kind: "challenge",
      eyebrow: "The current read",
      headline: "Waiting for the finished building before publishing may be late.",
      evidence: "Shortlists and peer posts are circulating names and decisions before photographs exist.",
      whyItMatters: "If the hypothesis is that proof follows completion, this sample challenges it.",
      briefRead: "We may need to revisit that. It is still a hypothesis. The principals decide what can be said in public.",
      possibleMove: "",
      signalIds: ["field-tender", "field-decisions"],
      evidenceIds: [],
      temporal: "divergence",
      strategyRelation: "challenge",
      hypothesisId: "proof-after-completion",
      epistemicStatus: "hypothesis",
      origin: "demo",
      rank: 3,
      bucket: "week",
    }),
    item({
      id: "field-watch",
      kind: "watch",
      eyebrow: "Regulation",
      headline: "A consultation wants decisions written down.",
      evidence: "Demo regulatory item. It is about records, not about a look.",
      whyItMatters: "It rhymes with the proof this practice already needs for specifiers. It is not a campaign.",
      briefRead: "Worth knowing. Not worth a post.",
      possibleMove: "",
      signalIds: ["field-rules"],
      evidenceIds: [],
      temporal: "novelty",
      strategyRelation: "not_affect",
      hypothesisId: "",
      epistemicStatus: "observation",
      origin: "demo",
      rank: 4,
      bucket: "watching",
    }),
    item({
      id: "field-noise",
      kind: "non_actionable",
      eyebrow: "Social",
      headline: "One LinkedIn post travelled once.",
      evidence: "Demo sample. No second post followed it.",
      whyItMatters: "Engagement spikes get mistaken for a channel strategy.",
      briefRead: "This probably doesn't matter.",
      possibleMove: "",
      signalIds: ["field-linkedin"],
      evidenceIds: [],
      temporal: "once",
      strategyRelation: "not_affect",
      hypothesisId: "",
      epistemicStatus: "observation",
      origin: "demo",
      rank: 6,
      bucket: "watching",
    }),
  ];

  return {
    signals,
    catalogue,
    revisions: [
      {
        version: 1,
        at: daysAgo(now, 70),
        summary: "First read",
        previous: "",
        current: "Specifiers meet the practice long before a building is finished. Proof has to work on that clock.",
        why: "Discovery.",
        evidenceIds: [],
        managerDecisionIds: [],
      },
    ] satisfies BrainRevision[],
    competitors: [
      competitor({
        id: "field-peer",
        name: "A peer practice",
        website: "",
        socialHandles: [],
        relationship: "direct",
        monitoredSources: ["demo-social", "demo-news"],
        lastCheckedAt: daysAgo(now, 1),
        origin: "demo",
        snapshots: [
          { at: daysAgo(now, 90), origin: "demo", note: "Project photographs after completion.", metrics: {} },
          { at: daysAgo(now, 15), origin: "demo", note: "A decision note, before photographs.", metrics: {} },
        ],
      }),
    ],
    jobs: jobsFor(brandId, now),
    weekly: {
      persisted: ["Decision-led posts are new, not yet a six-week pattern."],
      disappeared: ["The single LinkedIn spike."],
      convergence: ["Shortlists and peer posts both circulate names before buildings exist."],
      customerLanguage: ["Architect for a building type. Not dream home."],
      searchMovement: ["Specifier-shaped queries rose in the demo sample."],
      opportunities: ["One forwardable note: the decision and the constraint."],
      hypothesesStrengthened: ["Principal expertise, shown as a decision, is the proof."],
      hypothesesWeakened: ["Proof should wait for the finished photograph."],
      decisionsToReconsider: ["Publishing only after completion."],
    },
  };
}

function kiln(brandId: string, now: string) {
  const signals: Signal[] = [
    signal({
      id: "kiln-quiet",
      brandId,
      type: "social_topic_change",
      sourceType: "social",
      sourceProvider: "demo-social",
      title: "No theme moved in the demo sample",
      description: "The demo check ran. Topics around tableware did not shift enough to record a change.",
      observedAt: daysAgo(now, 1),
      periodStart: daysAgo(now, 7),
      periodEnd: daysAgo(now, 1),
      entity: "Tableware sample",
      entityId: "kiln-sample",
      metric: "theme_shift",
      previousValue: "Steady",
      currentValue: "Steady",
      change: "None",
      origin: "demo",
      firstObservedAt: daysAgo(now, 7),
      lastObservedAt: daysAgo(now, 1),
      metadata: { temporal: "persistence", themes: "tableware" },
    }),
  ];
  return {
    signals,
    catalogue: [] as IntelligenceItem[],
    revisions: [] as BrainRevision[],
    competitors: [] as MonitoredCompetitor[],
    jobs: jobsFor(brandId, now),
    weekly: {
      persisted: [],
      disappeared: [],
      convergence: [],
      customerLanguage: [],
      searchMovement: [],
      opportunities: [],
      hypothesesStrengthened: [],
      hypothesesWeakened: [],
      decisionsToReconsider: [],
    },
  };
}
